import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const plexMono = IBM_Plex_Mono({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                <link
                    rel="stylesheet"
                    href="https://use.typekit.net/eet3xfm.css"
                ></link>
            </Head>

            <body className={plexMono.className}>{children}</body>
        </html>
    );
}
